version: '3.8'
services:

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./arwi_reverse_proxy_docker.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8777:80
      - 8443:443
    networks:
      - arwi_network
    restart: always

  frontend_ui:
    image: chelliryc/arwi-frontend-ui:0.1.3.15
    networks:
      - arwi_network
    expose:
      - "7777"
    restart: always
    deploy:
      replicas: 1

  grammar_correction:
    image:  chelliryc/arwi-grammar-correction:0.1.3
    deploy:
      replicas: 1
    expose:
      - "9999"
    networks:
      - arwi_network
    restart: always

  essay_scoring:
    image: chelliryc/arwi-essay-scoring:0.1.3
    deploy:
      replicas: 1
    expose:
      - "9998"
    networks:
      - arwi_network
    restart: always
  
  backend:
    image: chelliryc/arwi-backend:0.1.4
    expose:
      - "9997"
    networks:
      - arwi_network
    restart: always
    deploy:
      replicas: 1
  
  postgres:
    image: postgres:17.2
    container_name: postgres_container
    environment:
      - POSTGRES_USER=arwi
      - POSTGRES_PASSWORD=arwi
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - 15432:5432
    restart: always
    command: -c config_file=/etc/postgresql/postgresql.conf

networks:
  arwi_network: