apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "arwi"
        - name: POSTGRES_PASSWORD
          value: "arwi"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        - mountPath: /etc/postgresql/postgresql.conf
          name: postgres-config
          subPath: postgresql.conf
        - mountPath: /etc/postgresql/pg_hba.conf
          name: postgres-config
          subPath: pg_hba.conf
        resources:
          requests:
            cpu: "4"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-config
        configMap:
          name: postgres-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 500
    shared_buffers = 2GB
    work_mem = 4MB
    maintenance_work_mem = 512MB
    effective_cache_size = 6GB
    max_wal_size = '1GB'
    min_wal_size = '80MB'
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    max_worker_processes = 8
    max_parallel_workers = 8
    max_parallel_workers_per_gather = 4

  pg_hba.conf: |
    host    all    all    0.0.0.0/0    md5
    host    all    all    ::/0    md5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 35432
  selector:
    app: postgres